#version 450

struct Particle
{
    vec3 position;
    vec3 velocity;
    vec4 color;
};

layout (std140, binding = 1) buffer ParticleSSBOIn
{
    Particle particlesIn[];
};

layout (std140, binding = 2) buffer ParticleSSBOOut
{
    Particle particlesOut[];
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    particlesOut[index] = particlesIn[index];
}